name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Deps
        run: npm ci

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: src/.vuepress/dist
  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GITHUB }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 8.141.48.181 >> ~/.ssh/known_hosts
          git config --global user.name 'huxzhi'
          git config --global user.email 'huxzhi@gmail.com'
      - name: Deploy
        run: |
          ssh git@8.141.48.181 "git config --global --add safe.directory /var/www"
          git push -f git@8.141.48.181:/var/www gh-pages
          ssh git@8.141.48.181 "cd /var/www && git reset --hard HEAD"
